# Generated by Django 5.1.3 on 2024-11-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('genre_title', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('hall_title', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('movie_title', models.CharField()),
                ('release_date', models.DateField()),
                ('age_limit', models.PositiveIntegerField()),
                ('duration_time', models.TimeField()),
                ('genres', models.ManyToManyField(to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.hall')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('purchase_time', models.DateTimeField()),
                ('row', models.PositiveIntegerField()),
                ('seat', models.PositiveIntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.client')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.session')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('row_num', models.PositiveIntegerField()),
                ('num_seats', models.PositiveIntegerField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.hall')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('row_num__gte', 1)), name='num_row_gte_1'), models.CheckConstraint(condition=models.Q(('num_seats__gte', 1)), name='num_seats_gte_1')],
            },
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('seat__gte', 1)), name='seat_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('row__gte', 1)), name='row_gte_1'),
        ),
    ]
